# Generated by Django 5.2.17 on 2026-09-11 21:57

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(default="IN", max_length=2)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                ("company_name", models.CharField(max_length=255)),
                ("isin", models.CharField(blank=True, db_index=True, max_length=12)),
                ("sector", models.CharField(blank=True, db_index=True, max_length=128)),
                ("industry", models.CharField(blank=True, max_length=128)),
                (
                    "security_type",
                    models.CharField(
                        choices=[
                            ("equity", "Equity"),
                            ("etf", "ETF"),
                            ("index", "Index"),
                        ],
                        default="equity",
                        max_length=16,
                    ),
                ),
                ("listing_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="securities",
                        to="market.exchange",
                    ),
                ),
            ],
            options={
                "ordering": ["exchange__code", "symbol"],
            },
        ),
        migrations.CreateModel(
            name="DailyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "adjusted_close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=20,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("volume", models.PositiveBigIntegerField()),
                ("source", models.CharField(max_length=64)),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="market.security",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "security_id"],
            },
        ),
        migrations.AddIndex(
            model_name="security",
            index=models.Index(
                fields=["exchange", "is_active"], name="security_exchange_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="security",
            constraint=models.UniqueConstraint(
                fields=("exchange", "symbol"), name="security_exchange_symbol_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyprice",
            constraint=models.UniqueConstraint(
                fields=("security", "date"), name="price_security_date_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyprice",
            constraint=models.CheckConstraint(
                condition=models.Q(("high__gte", models.F("low"))),
                name="price_high_gte_low",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyprice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("open__gte", 0), ("close__gte", 0), ("low__gte", 0)
                ),
                name="price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyprice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("open__gte", models.F("low")),
                    ("open__lte", models.F("high")),
                    ("close__gte", models.F("low")),
                    ("close__lte", models.F("high")),
                ),
                name="price_ohlc_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyprice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("adjusted_close__isnull", True),
                    ("adjusted_close__gte", 0),
                    _connector="OR",
                ),
                name="price_adjusted_nonnegative",
            ),
        ),
    ]
