# Generated by Django 5.2.17 on 2026-09-11 22:05

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="exchange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "code",
                        django.db.models.functions.text.Upper(
                            django.db.models.functions.text.Trim(models.F("code"))
                        ),
                    ),
                    models.Q(("code", ""), _negated=True),
                ),
                name="exchange_code_canonical",
            ),
        ),
        migrations.AddConstraint(
            model_name="security",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "symbol",
                        django.db.models.functions.text.Upper(
                            django.db.models.functions.text.Trim(models.F("symbol"))
                        ),
                    ),
                    models.Q(("symbol", ""), _negated=True),
                ),
                name="security_symbol_canonical",
            ),
        ),
    ]
