# Generated by Django 5.2.17 on 2026-09-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("market", "0002_exchange_exchange_code_canonical_and_more")]

    operations = [
        migrations.CreateModel(
            name="SecurityExternalIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=64)),
                ("identifier", models.CharField(max_length=128)),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_identifiers",
                        to="market.security",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="securityexternalidentifier",
            constraint=models.UniqueConstraint(
                fields=("security", "provider"),
                name="security_provider_identifier_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="securityexternalidentifier",
            constraint=models.UniqueConstraint(
                fields=("provider", "identifier"), name="provider_identifier_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="securityexternalidentifier",
            index=models.Index(
                fields=["provider", "identifier"], name="provider_identifier_idx"
            ),
        ),
    ]
