# Generated by Django 5.2.17 on 2026-09-11 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("dataset", models.CharField(default="daily_prices", max_length=64)),
                ("symbol", models.CharField(max_length=32)),
                ("exchange", models.CharField(max_length=16)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("rows_received", models.PositiveIntegerField(default=0)),
                ("rows_inserted", models.PositiveIntegerField(default=0)),
                ("rows_updated", models.PositiveIntegerField(default=0)),
                ("rows_failed", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["status", "started_at"], name="run_status_started_idx"
                    ),
                    models.Index(
                        fields=["provider", "started_at"],
                        name="run_provider_started_idx",
                    ),
                ],
            },
        ),
    ]
